#define DLG_PROPERTIES              100
#define ST_KEYLOW                   104
#define ST_KEYMEDIUM                105
#define ST_KEYHEAVY                 106
#define ST_MOUSEMEDIUM              111
#define ST_MOUSEHEAVY               112
#define ST_MOUSELOW                 114
#define ST_STATUSYELLOW             115
#define ST_STATUSRED                116
#define ST_STATUSGREEN              118
#define PB_OK                       119
#define PB_CANCEL                   120
#define GB_STATUS                   121
#define GB_MOUSE                    122
#define CB_BEEP                     101
#define GB_GENERAL                  113
#define CB_CREATELOG                124
#define PB_HELP                     126
#define EF_COMPUTERNAME             127
#define ST_COMPUTERNAME             128
#define EF_LOGFILENAME              117
#define ST_VIEWER                   123
#define EF_VIEWER                   129
#define SB_KEYLOW                   130
#define SB_KEYHIGH                  131
#define SB_MOUSELOW                 132
#define SB_MOUSEHIGH                133
#define SB_STATUSLOW                134
#define SB_STATUSHIGH               135
